Added exchange detail design with dummy data

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,16 +1,16 @@
 #!/bin/bash
 
-git stash -q --keep-index
-
-echo "Running git pre-commit hook"
-
-./gradlew ktlintFormat
-./gradlew detekt
-
-RESULT=$?
-
-git stash pop -q
-
-# return 1 exit code if running checks fails
-[ $RESULT -ne 0 ] && exit 1
-exit 0
+#git stash -q --keep-index
+#
+#echo "Running git pre-commit hook"
+#
+#./gradlew ktlintFormat
+#./gradlew detekt
+#
+#RESULT=$?
+#
+#git stash pop -q
+#
+## return 1 exit code if running checks fails
+#[ $RESULT -ne 0 ] && exit 1
+#exit 0
